### ISSUE TITLE
Preview Dataframe when hovering Trrack on a Node in TrrackVis

### ISSUE THREAD

**Issue by kirangadhave** [visdesignlab/persist#3]
Show the first ~5 rows of the dataframe in a really compact non-interactive table by hovering on some icon in a trrack-vis node.

**Comment by NateLanza** [comment]
- Use mantine popover
- Needs to get the cached dataframe
- Ideally first 5/last 5 columns

**Comment by NateLanza** [comment]
We need to be able to pass custom tooltips to Trrack to have this work. The tooltip would assumably be a callback function that takes the Trrack state as its only parameter and returns a component. So this is precluded by an update to trrackvis

**Comment by NateLanza** [comment]
5/23/24 meeting decided this feature is no longer wanted; instead we want an option to switch to table view when looking at a vis.
