### ISSUE TITLE
Add better aggregate controls

### ISSUE THREAD

**Issue by kirangadhave** [visdesignlab/persist#47]
We have a single Aggregate button which aggregates with the mean operation. It would be useful to have multiple controls for options like: `Aggregate Sum,` `Aggregate Mean,` `Aggregate Group-By.`

`Aggregate Group-by` creates the group-by object without any operation specified. In terms of visualization, we can show this by a convex hull (maybe?) instead of adding the aggregate point and removing the original points.

**Comment by kirangadhave** [comment]
We have a single `Aggregate` button which aggregates with the `mean` operation. It would be useful to have multiple controls for options like: `Aggregate Sum`, `Aggregate Mean`,  `Aggregate Group-By`

**Comment by alexsb** [comment]
It creates a group-by object instead of a dataframe, where the aggregate function can later be specified in code.

**Comment by kirangadhave** [comment]
ah that makes sense.

**Comment by kirangadhave** [comment]
To check:

- add warning when aggregating with sum operation, if the field is not aggregate encoding
