### ISSUE TITLE
Add categorize operation

### ISSUE THREAD

**Issue by kirangadhave** [visdesignlab/persist#49]
Currently, `aggregate` adds a new column called `__aggregate` to attach an aggregate name to each row. We should have an explicit Categorize operation that lets us add a `__cateogry` column that can be named.

Only one category for the CHI prototype, but ideally should allow adding any number of category columns.

**Comment by kirangadhave** [comment]
@alexsb To visually show the category assignment, should we encode the new category as mark type or mark color (preference to mark type if available)?

**Comment by alexsb** [comment]
Hmm, that's hard, no? It could already use either. I think there are two ways: 

* Either do a simple solution (mark shape is less likely taken) and acknowledge the problem. 
* Do something more complicated such as under-laying a separate mark, or drawing a set vis (line sets, bubble sets) on top

**Comment by kirangadhave** [comment]
It’s easy to determine if mark/color is encoded or just has fixed value. Vegalite has inbuilt functions for this. We can use that and if mark/color has fixed value we can use that to encode, else show a warning and print out the column name, so they can use it if they like to update Altair code and use it to encode

**Comment by alexsb** [comment]
Sounds like a plan
