### ISSUE TITLE
Add label change operations.

### ISSUE THREAD

**Issue by kirangadhave** [visdesignlab/persist#53]
we should have operations to change labels for rows or columns. 

### Row
Should we specify the label column? If there is no label column, should we add one?

### Column
I assume this is the same as #55?

**Comment by kirangadhave** [comment]
@alexsb I think this was also regarding renaming the aggregate (or any other category labels). I am marking this as a duplicate; let me know if you mean something else by changing labels.

**Comment by kirangadhave** [comment]
Duplicate of #52

**Comment by alexsb** [comment]
We should be able to change labels of any row or column. I don't think this is a duplicate, as this doesn't relate to aggregates.

**Comment by kirangadhave** [comment]
makes sense I will update the description

**Comment by alexsb** [comment]
Yes, if there's no label column, we should add one.

**Comment by kirangadhave** [comment]
Column value change
