### ISSUE TITLE
Fix width of trrack

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/persist#99]
Should be as wide as possible

**Comment by kirangadhave** [comment]
@ZachCutler04 I am stuck with this issue because of the way TrrackVis width works. I posted about my understanding of the issue in Slack.

>  It seems that Trrack-Vis is taking width of the backbone nodes as argument. I am guessing nodeWidthShown is the prop. In any case, there is a fixed width added to the div with labels. Since the parent of the div is a flex, we can set the width attribute to 100% an let it take all the remaining width. We can constrain the width of TrrackVis to whatever we want by wrapping it in a div with width when we use it.

If I'm missing something please let me know
